{"name": "test_user_id_validation", "status": "broken", "statusDetails": {"message": "helpers.assertion_utils.ResponseStatusCodeNotMatchedException: Expected status code: 401 but found: 200 \n with response: {\"code\":\"1207\",\"message\":\"User Id not correct!\"}", "trace": "self = <tests.test_user.TestUsers object at 0x0000021662A32AF0>\n\n    def test_user_id_validation(self):\n        # Get user using random generated UUID\n        response = User.get_user_by_id(self.new_user_session, user_id=uuid.uuid4(), status_code=StatusCodes.UNAUTHORIZED)\n        assert_that(response.message).is_equal_to(\"User not found!\")\n    \n        # Delete user using random generated UUID\n        # BUG: Delete returns 200 error code with message: User Id not correct!\n>       response = User.delete_user(self.new_user_session, user_id=uuid.uuid4(), status_code=StatusCodes.UNAUTHORIZED)\n\ntests\\test_user.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nmodels\\user_models.py:57: in delete_user\n    verify_response_status_code(response, status_code)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>, expected_status_code = 401\n\n    def verify_response_status_code(response, expected_status_code):\n        if response.status_code != expected_status_code:\n>           raise ResponseStatusCodeNotMatchedException(f'Expected status code: {expected_status_code} but found: '\n                                                        f'{response.status_code} \\n with response: {response.text}')\nE           helpers.assertion_utils.ResponseStatusCodeNotMatchedException: Expected status code: 401 but found: 200 \nE            with response: {\"code\":\"1207\",\"message\":\"User Id not correct!\"}\n\nhelpers\\assertion_utils.py:7: ResponseStatusCodeNotMatchedException"}, "start": 1662885235083, "stop": 1662885235190, "uuid": "96f500c7-6b29-47d3-9fcb-5c9687a051c0", "historyId": "41f7c01028cf42d0c915e78eeee59087", "testCaseId": "527027483f032ac0e2ea7fa2536966a0", "fullName": "tests.test_user.TestUsers#test_user_id_validation", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "DESKTOP-6B2AP20"}, {"name": "thread", "value": "15516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}